const languageMap = {
  '🇧🇬': 'BG',
  '🇨🇳': 'ZH',
  '🇨🇿': 'CS',
  '🇩🇰': 'DA',
  '🇳🇱': 'NL',
  '🇬🇧': 'EN-GB',
  '🏴󠁧󠁢󠁥󠁮󠁧󠁿': 'EN-GB',
  '🇺🇸': 'EN-US',
  '🇺🇲': 'EN-US',
  '🇪🇪': 'ET',
  '🇫🇮': 'FI',
  '🇫🇷': 'FR',
  '🇩🇪': 'DE',
  '🇬🇷': 'EL',
  '🇭🇺': 'HU',
  '🇮🇹': 'IT',
  '🇯🇵': 'JA',
  '🇱🇻': 'LV',
  '🇱🇹': 'LT',
  '🇵🇱': 'PL',
  '🇵🇹': 'PT-PT',
  '🇧🇷': 'PT-BR',
  '🇷🇴': 'RO',
  '🇷🇺': 'RU',
  '🇸🇰': 'SK',
  '🇸🇮': 'SL',
  '🇪🇸': 'ES',
  '🇪🇦': 'ES',
  '🇸🇪': 'SV',
};
exports.languageMap = languageMap;
